### ISSUE TITLE
OTOS Sensor resetTracking inconsistant

### ISSUE THREAD

**Issue by cjhardesty1** [Beta8397/virtual_robot#113]
When I tried to implement the myOtos.resetTracking(); command it doesn't seem to work or at least not consistantly. Are you aware of any issues with this?

**Comment by jkenney2** [comment]
I will look into it.

**Comment by jkenney2** [comment]
The problem is fixed. Thanks for the heads up and please let me know if it doesn't work for you.

**Comment by cjhardesty1** [comment]
It's still not working for me. Maybe I'm doing something wrong. Here's a quick test that I wrote. If I'm not mistaken this should just move the 20 inches and then reset the tracking to 0 and display that as telemetry data. But the telemetry just stays at 20 for the X and never resets:

package org.firstinspires.ftc.teamcode;

import com.qualcomm.hardware.sparkfun.SparkFunOTOS;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;

import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;

import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.DistanceUnit;

/**
 * Example OpMode. Demonstrates use of gyro, color sensor, encoders, and telemetry.
 *
 */
@Autonomous(name = "Mecanum Bot OTOS Reset Test", group = "MecanumBot")
public class OTOSSensorResetTest extends LinearOpMode {

    SparkFunOTOS myOtos;
    DcMotorEx m1, m2, m3, m4;
    SparkFunOTOS.Pose2D pos;


    public void runOpMode() throws InterruptedException{
        myOtos = hardwareMap.get(SparkFunOTOS.class, "sensor_otos");

        m1 = hardwareMap.get(DcMotorEx.class, "back_left_motor");
        m2 = hardwareMap.get(DcMotorEx.class, "front_left_motor");
        m3 = hardwareMap.get(DcMotorEx.class, "front_right_motor");
        m4 = hardwareMap.get(DcMotorEx.class, "back_right_motor");
        m1.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        m2.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        m3.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        m4.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        m1.setDirection(DcMotorSimple.Direction.REVERSE);
        m2.setDirection(DcMotorSimple.Direction.REVERSE);

        pos = myOtos.getPosition();

        configureOtos();

        // Log the position to the telemetry
        telemetry.addData("Press Start When Ready","");
        telemetry.addData("X coordinate", pos.x);
        telemetry.addData("Y coordinate", pos.y);
        telemetry.addData("Heading angle", pos.h);
        telemetry.update();

        waitForStart();

            //Drive forward 20 inches
            while (pos.x < 20.0) {
                pos = myOtos.getPosition();
                m1.setPower(1);
                m2.setPower(1);
                m3.setPower(1);
                m4.setPower(1);
            }
            //Stop robot
            m1.setPower(0);
            m2.setPower(0);
            m3.setPower(0);
            m4.setPower(0);

            //Reset tracking
            myOtos.resetTracking();

            // Log the position to the telemetry
            telemetry.addData("X coordinate", pos.x);
            telemetry.addData("Y coordinate", pos.y);
            telemetry.addData("Heading angle", pos.h);
            telemetry.update();
            
            //Sleep for 5 seconds so we can read telemetry and see if it reset
            sleep(5000);

    }
    //OTOS Configuration
    private void configureOtos() {
        telemetry.addLine("Configuring OTOS...");
        telemetry.update();
        myOtos.setLinearUnit(DistanceUnit.INCH);
        myOtos.setAngularUnit(AngleUnit.DEGREES);
        SparkFunOTOS.Pose2D offset = new SparkFunOTOS.Pose2D(0, 0, 0);
        myOtos.setOffset(offset);
        myOtos.setLinearScalar(1.0);
        myOtos.setAngularScalar(1.0);
        myOtos.calibrateImu();
        myOtos.resetTracking();
        SparkFunOTOS.Pose2D currentPosition = new SparkFunOTOS.Pose2D(0, 0, 0);
        myOtos.setPosition(currentPosition);
        SparkFunOTOS.Version hwVersion = new SparkFunOTOS.Version();
        SparkFunOTOS.Version fwVersion = new SparkFunOTOS.Version();
        myOtos.getVersionInfo(hwVersion, fwVersion);
        telemetry.addLine("OTOS configured! Press start to get position data!");
        telemetry.addLine();
        telemetry.addLine(String.format("OTOS Hardware Version: v%d.%d", hwVersion.major, hwVersion.minor));
        telemetry.addLine(String.format("OTOS Firmware Version: v%d.%d", fwVersion.major, fwVersion.minor));
        telemetry.update();
    }
}

**Comment by jkenney2** [comment]
I tried this out, reproduced what you reported, then noticed the following:

After you reset tracking, but before you report the position using telemetry, you need to update your 'pos' variable as follows:

pos = myOtos.getPosition();

Otherwise, you are just reporting the pos that was obtained during the final iteration of your 'while' loop. 

After adding that, it worked properly for me.

**Comment by cjhardesty1** [comment]
ahhhh....I thought maybe it was something simple I was missing. Thanks!!!
